### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Ascenio** [willeccles/cfm#25]
I would like to know your opinion about:
- Splitting the project into multiple files
- Changing error codes from ints to enums
- Removing logic from main switch into dedicated functions
- Remove the goto's

**Comment by willeccles** [comment]
None of these are priorities for me. While I understand that the code is godawful and hideous, about half of the fun of the project was writing it that way, since I usually put a lot of effort into making code as good as it can be. Most of this project is centered around simplicity, even in the code, so everything is very simple, albeit ugly. I will say this, however: taking the drawing code out of this and writing my own drawing library for other programs will allow me to do a massive rewrite and simplification of cfm, so for now I will leave it as-is. However, PRs are welcome, as long as you test that all functionality still works.

**Comment by willeccles** [comment]
I should add that this project started mainly as a joke with friends and only once it was nearing the state it's in now did I realize I could make it a publicly available thing, so it has a certain meme aspect to it :)

**Comment by willeccles** [comment]
Actually, let me further add this: I was considering splitting the switch into multiple functions, I just didn't get around to it and eventually it got big and hairy like it is now so I just left it. That is one thing that I agree with you on for sure.
